server:
  port: 8080

payment:
  base-url: http://localhost:8083
  currency: EUR
  method: CARD

wms:
  base-url: http://localhost:8084 

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
